# Generated by Django 3.0.3 on 2020-12-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('running_time', models.IntegerField(default=0)),
            ],
        ),
    ]
