# Generated by Django 3.0.3 on 2020-12-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttApp', '0002_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
